version: '2'
services:
  wilson:
    build: .
    ports:
    - "3000:3000"
    links:
    - rethinkdb
    environment:
      DB_NAME: "wilson"
      DB_URL: "//rethinkdb:28015"
  rethinkdb:
    image: rethinkdb
    ports:
    - "8080:8080"
    volumes:
    - .:/data
